/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AdminAnalytics = IDL.Record({
  'totalViews' : IDL.Nat,
  'totalVideos' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalComments' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'handle' : IDL.Text,
  'channelDescription' : IDL.Text,
  'avatar' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});
export const Time = IDL.Int;
export const VideoMetadata = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'isShort' : IDL.Bool,
  'description' : IDL.Text,
  'videoFile' : ExternalBlob,
  'viewCount' : IDL.Nat,
  'uploader' : IDL.Principal,
  'uploadDate' : Time,
});
export const AdminDashboard = IDL.Record({
  'analytics' : AdminAnalytics,
  'users' : IDL.Vec(UserProfile),
  'videos' : IDL.Vec(VideoMetadata),
});
export const ApiKey = IDL.Record({
  'key' : IDL.Text,
  'active' : IDL.Bool,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'apiLabel' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'videoId' : IDL.Text,
});
export const CommunityPost = IDL.Record({
  'id' : IDL.Text,
  'body' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'attachment' : IDL.Opt(ExternalBlob),
});
export const MonetizationStats = IDL.Record({
  'monetizationStatus' : IDL.Text,
  'totalEarnings' : IDL.Nat,
  'estimatedRevenue' : IDL.Nat,
});
export const PlaylistView = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Text,
  'videos' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addVideoToPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'adminRemoveUserProfile' : IDL.Func([IDL.Principal], [], []),
  'adminRemoveVideo' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearVideoComments' : IDL.Func([IDL.Text], [], []),
  'createApiKey' : IDL.Func([IDL.Text], [IDL.Text], []),
  'createCommunityPost' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Text],
      [],
    ),
  'createPlaylist' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'deleteComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteCommunityPost' : IDL.Func([IDL.Text], [], []),
  'deletePlaylist' : IDL.Func([IDL.Text], [], []),
  'getAdminDashboard' : IDL.Func([], [AdminDashboard], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
  'getApiKeys' : IDL.Func([], [IDL.Vec(ApiKey)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannelVideoCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getChannelVideos' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(VideoMetadata)],
      ['query'],
    ),
  'getCommentCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getCommunityPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
  'getCommunityPostsByChannel' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CommunityPost)],
      ['query'],
    ),
  'getMonetizationStats' : IDL.Func([], [MonetizationStats], ['query']),
  'getPlaylistById' : IDL.Func([IDL.Text], [IDL.Opt(PlaylistView)], ['query']),
  'getPlaylistVideos' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(VideoMetadata)],
      ['query'],
    ),
  'getPlaylistsByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PlaylistView)],
      ['query'],
    ),
  'getSubscribedShorts' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
  'getSubscriberCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getSubscribers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getTrendingVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSubscriptions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getVideo' : IDL.Func([IDL.Text], [IDL.Opt(VideoMetadata)], ['query']),
  'incrementViewCount' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeVideoFromPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'revokeApiKey' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoMetadata)], ['query']),
  'subscribeToChannel' : IDL.Func([IDL.Principal], [], []),
  'unsubscribeFromChannel' : IDL.Func([IDL.Principal], [], []),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  'uploadVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob, IDL.Bool],
      [IDL.Text],
      [],
    ),
  'validateApiKey' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AdminAnalytics = IDL.Record({
    'totalViews' : IDL.Nat,
    'totalVideos' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalComments' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'handle' : IDL.Text,
    'channelDescription' : IDL.Text,
    'avatar' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const Time = IDL.Int;
  const VideoMetadata = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'isShort' : IDL.Bool,
    'description' : IDL.Text,
    'videoFile' : ExternalBlob,
    'viewCount' : IDL.Nat,
    'uploader' : IDL.Principal,
    'uploadDate' : Time,
  });
  const AdminDashboard = IDL.Record({
    'analytics' : AdminAnalytics,
    'users' : IDL.Vec(UserProfile),
    'videos' : IDL.Vec(VideoMetadata),
  });
  const ApiKey = IDL.Record({
    'key' : IDL.Text,
    'active' : IDL.Bool,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'apiLabel' : IDL.Text,
  });
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'videoId' : IDL.Text,
  });
  const CommunityPost = IDL.Record({
    'id' : IDL.Text,
    'body' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'attachment' : IDL.Opt(ExternalBlob),
  });
  const MonetizationStats = IDL.Record({
    'monetizationStatus' : IDL.Text,
    'totalEarnings' : IDL.Nat,
    'estimatedRevenue' : IDL.Nat,
  });
  const PlaylistView = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Text,
    'videos' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addVideoToPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'adminRemoveUserProfile' : IDL.Func([IDL.Principal], [], []),
    'adminRemoveVideo' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearVideoComments' : IDL.Func([IDL.Text], [], []),
    'createApiKey' : IDL.Func([IDL.Text], [IDL.Text], []),
    'createCommunityPost' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Text],
        [],
      ),
    'createPlaylist' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'deleteComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteCommunityPost' : IDL.Func([IDL.Text], [], []),
    'deletePlaylist' : IDL.Func([IDL.Text], [], []),
    'getAdminDashboard' : IDL.Func([], [AdminDashboard], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
    'getApiKeys' : IDL.Func([], [IDL.Vec(ApiKey)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannelVideoCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getChannelVideos' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(VideoMetadata)],
        ['query'],
      ),
    'getCommentCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getCommunityPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
    'getCommunityPostsByChannel' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CommunityPost)],
        ['query'],
      ),
    'getMonetizationStats' : IDL.Func([], [MonetizationStats], ['query']),
    'getPlaylistById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PlaylistView)],
        ['query'],
      ),
    'getPlaylistVideos' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(VideoMetadata)],
        ['query'],
      ),
    'getPlaylistsByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PlaylistView)],
        ['query'],
      ),
    'getSubscribedShorts' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
    'getSubscriberCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getSubscribers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getTrendingVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSubscriptions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getVideo' : IDL.Func([IDL.Text], [IDL.Opt(VideoMetadata)], ['query']),
    'incrementViewCount' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeVideoFromPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'revokeApiKey' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoMetadata)], ['query']),
    'subscribeToChannel' : IDL.Func([IDL.Principal], [], []),
    'unsubscribeFromChannel' : IDL.Func([IDL.Principal], [], []),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    'uploadVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob, IDL.Bool],
        [IDL.Text],
        [],
      ),
    'validateApiKey' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };