/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountState {
  'withdrawals' : Array<Withdrawal>,
  'balanceCents' : bigint,
}
export interface AdminAnalytics {
  'totalViews' : bigint,
  'totalVideos' : bigint,
  'totalUsers' : bigint,
  'totalComments' : bigint,
}
export interface AdminDashboard {
  'analytics' : AdminAnalytics,
  'users' : Array<UserProfile>,
  'videos' : Array<VideoMetadata>,
}
export interface ApiKey {
  'key' : string,
  'active' : boolean,
  'owner' : Principal,
  'createdAt' : Time,
  'apiLabel' : string,
}
export interface Comment {
  'id' : string,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'videoId' : string,
}
export interface CommunityPost {
  'id' : string,
  'body' : string,
  'author' : Principal,
  'timestamp' : Time,
  'attachment' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export interface MonetizationStats {
  'monetizationStatus' : string,
  'totalEarnings' : bigint,
  'estimatedRevenue' : bigint,
}
export interface PlatformEarningsStats {
  'numCreators' : bigint,
  'totalBalanceCents' : bigint,
  'numPendingWithdrawals' : bigint,
  'numCompletedWithdrawals' : bigint,
  'pendingWithdrawalsCents' : bigint,
  'totalWithdrawalsCents' : bigint,
}
export interface PlaylistView {
  'id' : string,
  'title' : string,
  'owner' : Principal,
  'createdAt' : Time,
  'description' : string,
  'videos' : Array<string>,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'handle' : string,
  'channelDescription' : string,
  'avatar' : [] | [Uint8Array],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoMetadata {
  'id' : string,
  'title' : string,
  'duration' : bigint,
  'isShort' : boolean,
  'description' : string,
  'videoFile' : ExternalBlob,
  'viewCount' : bigint,
  'uploader' : Principal,
  'uploadDate' : Time,
}
export interface Withdrawal {
  'status' : WithdrawalStatus,
  'amountCents' : bigint,
  'timestamp' : Time,
}
export type WithdrawalStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'approved' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], undefined>,
  'addVideoToPlaylist' : ActorMethod<[string, string], undefined>,
  'adminGetEarningsStats' : ActorMethod<[], PlatformEarningsStats>,
  'adminRemoveUserProfile' : ActorMethod<[Principal], undefined>,
  'adminRemoveVideo' : ActorMethod<[string], undefined>,
  'adminSaveUserProfile' : ActorMethod<[UserProfile, Principal], undefined>,
  'approveWithdrawal' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelWithdrawal' : ActorMethod<[], undefined>,
  'clearVideoComments' : ActorMethod<[string], undefined>,
  'createApiKey' : ActorMethod<[string], string>,
  'createCommunityPost' : ActorMethod<[string, [] | [ExternalBlob]], string>,
  'createPlaylist' : ActorMethod<[string, string], string>,
  'deleteComment' : ActorMethod<[string, string], undefined>,
  'deleteCommunityPost' : ActorMethod<[string], undefined>,
  'deletePlaylist' : ActorMethod<[string], undefined>,
  'getAdminDashboard' : ActorMethod<[], AdminDashboard>,
  'getAllVideos' : ActorMethod<[], Array<VideoMetadata>>,
  'getApiKeys' : ActorMethod<[], Array<ApiKey>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannelVideoCount' : ActorMethod<[Principal], bigint>,
  'getChannelVideos' : ActorMethod<[Principal], Array<VideoMetadata>>,
  'getCommentCount' : ActorMethod<[string], bigint>,
  'getComments' : ActorMethod<[string], Array<Comment>>,
  'getCommunityPosts' : ActorMethod<[], Array<CommunityPost>>,
  'getCommunityPostsByChannel' : ActorMethod<[Principal], Array<CommunityPost>>,
  'getCreatorBankAccountState' : ActorMethod<[], AccountState>,
  'getCreatorBankBalanceCents' : ActorMethod<[], bigint>,
  'getHasUnapprovedWithdrawal' : ActorMethod<[], boolean>,
  'getMonetizationStats' : ActorMethod<[], MonetizationStats>,
  'getPlaylistById' : ActorMethod<[string], [] | [PlaylistView]>,
  'getPlaylistVideos' : ActorMethod<[string], Array<VideoMetadata>>,
  'getPlaylistsByOwner' : ActorMethod<[Principal], Array<PlaylistView>>,
  'getSubscribedShorts' : ActorMethod<[], Array<VideoMetadata>>,
  'getSubscriberCount' : ActorMethod<[Principal], bigint>,
  'getSubscribers' : ActorMethod<[Principal], Array<Principal>>,
  'getTrendingVideos' : ActorMethod<[], Array<VideoMetadata>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSubscriptions' : ActorMethod<[Principal], Array<Principal>>,
  'getVideo' : ActorMethod<[string], [] | [VideoMetadata]>,
  'incrementViewCount' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeLastPendingWithdrawal' : ActorMethod<[], undefined>,
  'removeVideoFromPlaylist' : ActorMethod<[string, string], undefined>,
  'requestWithdrawal' : ActorMethod<[bigint], undefined>,
  'revokeApiKey' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchVideos' : ActorMethod<[string], Array<VideoMetadata>>,
  'simulateAdminBankPayment' : ActorMethod<[bigint], undefined>,
  'subscribeToChannel' : ActorMethod<[Principal], undefined>,
  'unsubscribeFromChannel' : ActorMethod<[Principal], undefined>,
  'updateUserProfile' : ActorMethod<
    [string, string, string, [] | [Uint8Array]],
    undefined
  >,
  'uploadVideo' : ActorMethod<
    [string, string, bigint, ExternalBlob, boolean],
    string
  >,
  'validateApiKey' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];